name: Security Scan with Bandit

on:
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -r . -o bandit_report.json -f json || true

      - name: Analyze Scan Results
        run: |
          critical_vulns=$(jq '[.results[] | select(.issue_severity=="CRITICAL")] | length' bandit_report.json)
          if [ "$critical_vulns" -gt 0 ]; then
            gh pr comment ${{ github.event.pull_request.number }} --body "Block"
            exit 1
          else
            gh pr comment ${{ github.event.pull_request.number }} --body "Successful"
            gh pr merge ${{ github.event.pull_request.number }} --merge
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
